### ISSUE TITLE
Running self-made dataset requires DepthBounds.csv, but no instructions on how to obtain this file.

### ISSUE THREAD

**Issue by rdzhao** [NagabhushanSN95/ViP-NeRF#14]
python VisibilityMask02_NeRF_LLFF.py
Program started at 03/11/2023 10:43:47 PM
  0%|                                                                                                                    | 0/1 [00:00<?, ?it/s]
../../../data/databases/SELF/data/all/database_data/scene0001/DepthBounds.csv not found.
Traceback (most recent call last):
  File "/mnt/task_runtime/ViP-NeRF/src/prior_generators/visibility/VisibilityMask02_NeRF_LLFF.py", line 336, in <module>
    main()
  File "/mnt/task_runtime/ViP-NeRF/src/prior_generators/visibility/VisibilityMask02_NeRF_LLFF.py", line 328, in main
    demo1()
  File "/mnt/task_runtime/ViP-NeRF/src/prior_generators/visibility/VisibilityMask02_NeRF_LLFF.py", line 323, in demo1
    start_generation(gen_configs)
  File "/mnt/task_runtime/ViP-NeRF/src/prior_generators/visibility/VisibilityMask02_NeRF_LLFF.py", line 269, in start_generation
    bounds = numpy.loadtxt(bounds_path.as_posix(), delimiter=',')[frame_nums]
  File "/miniconda/envs/vipnerf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/miniconda/envs/vipnerf/lib/python3.9/site-packages/numpy/lib/npyio.py", line 992, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/miniconda/envs/vipnerf/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/miniconda/envs/vipnerf/lib/python3.9/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: ../../../data/databases/SELF/data/all/database_data/scene0001/DepthBounds.csv not found.
Program ended at 03/11/2023 10:43:47 PM
Execution time: 0:00:00.385838

`FileNotFoundError: ../../../data/databases/SELF/data/all/database_data/scene0001/DepthBounds.csv not found.`

I've changed to used my own dataset with some images and CameraIntrinsics.csv and CameraExtrinsics.csv.

**Comment by NagabhushanSN95** [comment]
`DepthBounds.csv` contains near and far depth for every image in the scene. It is a `csv` file with 2 columns (near and far) and number of rows equal to number of images.

Typically, colmap is run to obtain the camera poses of the images. `DepthBounds.csv` can be extracted from colmap output as done in [NerfLlffDataExtractor](https://github.com/NagabhushanSN95/ViP-NeRF/blob/main/src/database_utils/nerf_llff/data_organizers/DataExtractor01.py#L60--L134). This is similar to how NeRF obtains bounds for the scenes.

If the min and max depth are the same across the database, it can be hard-coded as done for [VisibilityMask01_RealEstate.py](https://github.com/NagabhushanSN95/ViP-NeRF/blob/main/src/prior_generators/visibility/VisibilityMask01_RealEstate.py#L233-L234).
