### ISSUE TITLE
Antialiasing set to True when extracting meshes

### ISSUE THREAD

**Issue by yankeesong** [NagabhushanSN95/ViP-NeRF#2]
Got the following error when running "python DataExtractor02_RegNeRF.py"

Traceback (most recent call last):
  File "/nobackup/users/yankeson/tencent/ViP-NeRF/src/database_utils/dtu/data_organizers/DataExtractor02_RegNeRF.py", line 95, in <module>
    main()
  File "/nobackup/users/yankeson/tencent/ViP-NeRF/src/database_utils/dtu/data_organizers/DataExtractor02_RegNeRF.py", line 87, in main
    demo1()
  File "/nobackup/users/yankeson/tencent/ViP-NeRF/src/database_utils/dtu/data_organizers/DataExtractor02_RegNeRF.py", line 82, in demo1
    data_extractor.extract_data(downsampling_factor=4)
  File "/nobackup/users/yankeson/tencent/ViP-NeRF/src/database_utils/dtu/data_organizers/DataExtractor02_RegNeRF.py", line 49, in extract_data
    self.extract_mask(src_mask_path, tgt_mask_path, downsampling_factor)
  File "/nobackup/users/yankeson/tencent/ViP-NeRF/src/database_utils/dtu/data_organizers/DataExtractor02_RegNeRF.py", line 55, in extract_mask
    down_mask = skimage.transform.rescale(mask, scale=1 / downsampling_factor, preserve_range=True,
  File "/nobackup/users/yankeson/miniconda3/envs/DL/lib/python3.10/site-packages/skimage/_shared/utils.py", line 316, in fixed_func
    return func(*args, **kwargs)
  File "/nobackup/users/yankeson/miniconda3/envs/DL/lib/python3.10/site-packages/skimage/transform/_warps.py", line 289, in rescale
    return resize(image, output_shape, order=order, mode=mode, cval=cval,
  File "/nobackup/users/yankeson/miniconda3/envs/DL/lib/python3.10/site-packages/skimage/transform/_warps.py", line 158, in resize
    raise ValueError("anti_aliasing must be False for boolean images")
ValueError: anti_aliasing must be False for boolean images.

Fixed it by setting antialiasing=False, but just to report in case.

**Comment by NagabhushanSN95** [comment]
Thank you @yankeesong. I will verify it once and update the code.

**Comment by NagabhushanSN95** [comment]
I have updated the code to fix this. Closing this issue.
