### ISSUE TITLE
Error while testing on DTU dataset using pre-trained models

### ISSUE THREAD

**Issue by HarshaMupparaju** [NagabhushanSN95/ViP-NeRF#9]
I downloaded the DTU pre-trained models and put them into the respective folders, the pre-trained models for train0044, train0045 and train0046 don't exist in the given [link](https://indianinstituteofscience-my.sharepoint.com/personal/nagabhushans_iisc_ac_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fnagabhushans%5Fiisc%5Fac%5Fin%2FDocuments%2FPublished%2FResearch%2F13%5FVSTURW%2Fruns&ga=1) for pre-trained models but the program seems to look for models in these cases as well as I got this error:

```
Loading model from: /home/harshamupparaju/Softwares/Anaconda/anaconda3/envs/ViP_NeRF_GPU/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [00:00<00:00, 4268.92it/s]
Average MaskedLPIPS05: /mnt/2tb-hdd/harshaM/ViP-NeRF/src/../runs/testing/test0046 - predicted_frames: nan
"['LPIPS05'] not in index"
Traceback (most recent call last):
  File "/mnt/2tb-hdd/harshaM/ViP-NeRF/src/qa/00_Common/src/AllMetrics05_DTU.py", line 128, in <module>
    qa_scores = main(args)
  File "/mnt/2tb-hdd/harshaM/ViP-NeRF/src/qa/00_Common/src/AllMetrics05_DTU.py", line 117, in main
    qa_scores = demo2(args)
  File "/mnt/2tb-hdd/harshaM/ViP-NeRF/src/qa/00_Common/src/AllMetrics05_DTU.py", line 85, in demo2
    qa_scores = run_all_qa(pred_videos_dirpath, database_dirpath, frames_datapath, pred_folder_name,
  File "/mnt/2tb-hdd/harshaM/ViP-NeRF/src/qa/00_Common/src/AllMetrics05_DTU.py", line 48, in run_all_qa
    SceneWiseGrouper.group_qa_scores(pred_videos_dirpath.parent, [test_num])
  File "/mnt/2tb-hdd/harshaM/ViP-NeRF/src/qa/00_Common/src/SceneWiseGrouper.py", line 31, in group_qa_scores
    grouped_qa_data = get_grouped_qa_scores(qa_data)
  File "/mnt/2tb-hdd/harshaM/ViP-NeRF/src/qa/00_Common/src/SceneWiseGrouper.py", line 20, in get_grouped_qa_scores
    grouped_qa_data = qa_data.groupby(by=group_column_names).mean().reset_index()[final_column_names]
  File "/home/harshamupparaju/Softwares/Anaconda/anaconda3/envs/ViP_NeRF_GPU/lib/python3.8/site-packages/pandas/core/frame.py", line 3511, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/home/harshamupparaju/Softwares/Anaconda/anaconda3/envs/ViP_NeRF_GPU/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5782, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/harshamupparaju/Softwares/Anaconda/anaconda3/envs/ViP_NeRF_GPU/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5845, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['LPIPS05'] not in index"
```
Please look into this.

**Comment by NagabhushanSN95** [comment]
Thanks. Yes, this is a bug. We do not have pre-trained DTU models for `train0044`, `train0045` and `train0046`. Disable the corresponding inference calls in `DtuTrainerTester01.py` (comment `demo1d`, `demo1e`, `demo1f`). This should solve the issue.

I have updated the [READEME.md](https://github.com/NagabhushanSN95/ViP-NeRF#inference-with-pre-trained-models) with the above clarification.
